SUCCESS = 'SUCCESS'
FAILED = 'FAILED'
STATUS = ((SUCCESS, SUCCESS), (FAILED, FAILED))
SUPER_ADMIN = 'SUPER_ADMIN'
ADMIN = 'ADMIN'
EMPLOYEE = 'EMPLOYEE'
ROLES = ((SUPER_ADMIN, SUPER_ADMIN),
         (ADMIN, ADMIN),
         (EMPLOYEE, EMPLOYEE))

MALE = 'MALE'
FEMALE = 'FEMALE'
OTHERS = 'OTHERS'
GENDER = ((MALE, MALE), (FEMALE, FEMALE), (OTHERS, OTHERS))