SUCCESS = 'SUCCESS'
FAILURE = 'FAILURE'
STATUS = ((SUCCESS, SUCCESS), (FAILURE, FAILURE))
SUPER_ADMIN = 'SUPER_ADMIN'
ADMIN = 'ADMIN'
EMPLOYEE = 'EMPLOYEE'
ROLES = ((SUPER_ADMIN, SUPER_ADMIN),
         (ADMIN, ADMIN),
         (EMPLOYEE, EMPLOYEE))

MALE = 'MALE'
FEMALE = 'FEMALE'
OTHERS = 'OTHERS'
GENDER = ((MALE, MALE), (FEMALE, FEMALE), (OTHERS, OTHERS))

# EMAIL = 'EMAIL'
# GOOGLE = 'GOOGLE'
# FACEBOOK = 'FACEBOOK'
# TWITTER = 'TWITTER'
# AUTH_PROVIDERS = ((EMAIL, EMAIL), (GOOGLE, GOOGLE), (FACEBOOK, FACEBOOK), (TWITTER, TWITTER))